#!/usr/bin/env sh
# Regenerates deploy/nginx/cloudflare-ips.conf from Cloudflare's published ranges:
#   https://www.cloudflare.com/ips-v4
#   https://www.cloudflare.com/ips-v6
#
# nginx trusts CF-Connecting-IP only from these addresses (real_ip module). Cloudflare
# changes the list rarely, but it does change: run this every few months (or when
# Cloudflare announces a change), review the diff, commit, then reload nginx:
#   docker compose --env-file deploy/.env.prod -f deploy/docker-compose.prod.yml restart nginx
#
# Usage: deploy/scripts/refresh-cloudflare-ips.sh [output-file]
set -eu

V4_URL="${CF_IPS_V4_URL:-https://www.cloudflare.com/ips-v4}"
V6_URL="${CF_IPS_V6_URL:-https://www.cloudflare.com/ips-v6}"
OUT="${1:-$(dirname "$0")/../nginx/cloudflare-ips.conf}"

tmp="$(mktemp)"
trap 'rm -f "$tmp" "$tmp.v4" "$tmp.v6"' EXIT

fetch() { # url outfile
    curl --fail --silent --show-error --location --max-time 20 "$1" -o "$2"
}

# Keep only well-formed CIDRs: a failed or hijacked download must never produce a config
# that trusts garbage. nginx would reject a bad line, but an empty list would silently
# stop honoring CF-Connecting-IP.
valid_v4() { grep -E '^([0-9]{1,3}\.){3}[0-9]{1,3}/[0-9]{1,2}$' "$1"; }
valid_v6() { grep -E '^[0-9A-Fa-f:]+/[0-9]{1,3}$' "$1"; }

fetch "$V4_URL" "$tmp.v4"
fetch "$V6_URL" "$tmp.v6"

n4="$(valid_v4 "$tmp.v4" | wc -l | tr -d ' ')"
n6="$(valid_v6 "$tmp.v6" | wc -l | tr -d ' ')"
if [ "$n4" -lt 5 ] || [ "$n6" -lt 3 ]; then
    echo "refusing to write: got $n4 IPv4 and $n6 IPv6 ranges (expected at least 5 and 3)" >&2
    exit 1
fi

{
    echo "# Cloudflare IP ranges trusted for CF-Connecting-IP (nginx real_ip module)."
    echo "# Generated by deploy/scripts/refresh-cloudflare-ips.sh on $(date -u +%Y-%m-%d). Do not edit by hand."
    echo "# Sources: $V4_URL and $V6_URL"
    echo
    echo "# IPv4"
    valid_v4 "$tmp.v4" | while read -r cidr; do echo "set_real_ip_from $cidr;"; done
    echo
    echo "# IPv6"
    valid_v6 "$tmp.v6" | while read -r cidr; do echo "set_real_ip_from $cidr;"; done
} > "$tmp"

mv "$tmp" "$OUT"
chmod 644 "$OUT"
echo "wrote $OUT ($n4 IPv4 and $n6 IPv6 ranges)"
